import numpy as np
import os

def write_obj_file(filename, vertices, faces):
    """
    Creates a simple .obj file from a list of vertices and faces.

    Args:
        filename (str): The name of the .obj file to create (e.g., "cube.obj").
        vertices (list): A list of tuples or lists, where each inner list/tuple
                         represents a vertex (x, y, z).
        faces (list): A list of tuples or lists, where each inner list/tuple
                      represents a face by referencing the 1-based index
                      of the vertices.
    """
    try:
        with open(filename, 'w') as f:
            # Write a header for the file
            f.write("# .obj file generated by a Python script\n")
            f.write(f"o {os.path.basename(filename).split('.')[0]}\n\n")

            # Write all the vertices
            f.write("# Vertices\n")
            for v in vertices:
                f.write(f"v {v[0]} {v[1]} {v[2]}\n")
            f.write("\n")

            # Write all the faces (using 1-based indexing for vertices)
            f.write("# Faces\n")
            for face in faces:
                f.write("f")
                for vertex_index in face:
                    f.write(f" {vertex_index}")
                f.write("\n")

        print(f"Successfully created '{filename}'")

    except IOError as e:
        print(f"Error writing to file: {e}")