name: crystal2shape
dependencies:
  - python=3.10
  - pip
  - pytest
  - pyvista
  - ase
  - pymatgen
  - hoomd
  - matplotlib
  - trimesh
  - scipy
  - numpy
  - spglib
  - scikit-learn
  - pip:
      - scikit-spatial
      - freud-analysis
      - rowan
      - gsd
      - coxeter
      - mpld3
      - parsnip-cif