[workspace]
path = "../../data/workspace"
value_file = "signac_statepoint.json"

[default.action]
command = "python ../compress_scripts/project.py --action $ACTION_NAME {directories}"

[[action]]
name = "initialize"
products = ["initialize.gsd"]
resources.walltime.per_directory = "00:10:00"

[[action]]
name = "compress" 
previous_actions = ["initialize"]
products = ["compress.gsd"]
resources.walltime.per_directory = "01:00:00"
[[action.group.include]]
condition = ["/compression", "==", true]


[[action]]
name = "equilibrate_compression"
previous_actions = ["initialize", "compress"]
products = ["trajectory.gsd"]
resources.walltime.per_directory = "00:10:00"
[[action.group.include]]
condition = ["/compression", "==", true]


[[action]]
name = "equilibrate_stability"
previous_actions = ["initialize"]
products = ["trajectory.gsd"]
resources.walltime.per_directory = "00:10:00"
[[action.group.include]]
condition = ["/compression", "==", false]


[[action]]
name = "analyze_compression"
previous_actions = ["equilibrate_compression"]
products = ["bod.mp4", "rdf.mp4", "bod2.mp4"]
resources.walltime.per_directory = "00:05:00"

[[action]]
name = "analyze_stability"
previous_actions = ["equilibrate_stability"]
products = ["bod.mp4", "rdf.mp4", "bod2.mp4"]
resources.walltime.per_directory = "00:05:00"