[workspace]
value_file = "signac_statepoint.json"

[default.action]
command = "python project.py --action $ACTION_NAME {directories}"

[[action]]
name = "equilibrate"
products = ["trajectory.gsd"]
resources.walltime.per_directory = "00:10:00"

[[action]]
name = "analyze"
previous_actions = ["equilibrate"]
products = ["finalframe_bod.html"]
resources.walltime.per_directory = "00:05:00"