[workspace]
path = "../../data/workspace"
value_file = "signac_statepoint.json"

[default.action]
command = "python ../compress_scripts/project.py --action $ACTION_NAME {directories}"

[[action]]
name = "initialize"
products = ["initialize.gsd"]
resources.walltime.per_directory = "00:10:00"

[[action]]
name = "equilibrate"
previous_actions = ["initialize"]
products = ["trajectory.gsd"]
resources.walltime.per_directory = "01:00:00"

[[action]]
name = "analyze"
previous_actions = ["equilibrate"]
products = ["bod.mp4", "rdf.mp4", "bod2.mp4"]
resources.walltime.per_directory = "00:05:00"